// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0--rc2
// source: inference.proto

package inferencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceService_EstimateVolume_FullMethodName   = "/nutrix.inference.InferenceService/EstimateVolume"
	InferenceService_AnalyzeMealImage_FullMethodName = "/nutrix.inference.InferenceService/AnalyzeMealImage"
)

// InferenceServiceClient is the client API for InferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceServiceClient interface {
	// Unary RPC: single image in, single volume estimate out.
	EstimateVolume(ctx context.Context, in *EstimateVolumeRequest, opts ...grpc.CallOption) (*EstimateVolumeResponse, error)
	// Consolidated E2E Pipeline: Image -> CV -> Enrichment -> KG Reasoning -> Recommendation
	AnalyzeMealImage(ctx context.Context, in *AnalyzeMealImageRequest, opts ...grpc.CallOption) (*AnalyzeMealImageResponse, error)
}

type inferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceServiceClient(cc grpc.ClientConnInterface) InferenceServiceClient {
	return &inferenceServiceClient{cc}
}

func (c *inferenceServiceClient) EstimateVolume(ctx context.Context, in *EstimateVolumeRequest, opts ...grpc.CallOption) (*EstimateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EstimateVolumeResponse)
	err := c.cc.Invoke(ctx, InferenceService_EstimateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) AnalyzeMealImage(ctx context.Context, in *AnalyzeMealImageRequest, opts ...grpc.CallOption) (*AnalyzeMealImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeMealImageResponse)
	err := c.cc.Invoke(ctx, InferenceService_AnalyzeMealImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServiceServer is the server API for InferenceService service.
// All implementations must embed UnimplementedInferenceServiceServer
// for forward compatibility.
type InferenceServiceServer interface {
	// Unary RPC: single image in, single volume estimate out.
	EstimateVolume(context.Context, *EstimateVolumeRequest) (*EstimateVolumeResponse, error)
	// Consolidated E2E Pipeline: Image -> CV -> Enrichment -> KG Reasoning -> Recommendation
	AnalyzeMealImage(context.Context, *AnalyzeMealImageRequest) (*AnalyzeMealImageResponse, error)
	mustEmbedUnimplementedInferenceServiceServer()
}

// UnimplementedInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServiceServer struct{}

func (UnimplementedInferenceServiceServer) EstimateVolume(context.Context, *EstimateVolumeRequest) (*EstimateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EstimateVolume not implemented")
}
func (UnimplementedInferenceServiceServer) AnalyzeMealImage(context.Context, *AnalyzeMealImageRequest) (*AnalyzeMealImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeMealImage not implemented")
}
func (UnimplementedInferenceServiceServer) mustEmbedUnimplementedInferenceServiceServer() {}
func (UnimplementedInferenceServiceServer) testEmbeddedByValue()                          {}

// UnsafeInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServiceServer will
// result in compilation errors.
type UnsafeInferenceServiceServer interface {
	mustEmbedUnimplementedInferenceServiceServer()
}

func RegisterInferenceServiceServer(s grpc.ServiceRegistrar, srv InferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceService_ServiceDesc, srv)
}

func _InferenceService_EstimateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EstimateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).EstimateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_EstimateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).EstimateVolume(ctx, req.(*EstimateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_AnalyzeMealImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeMealImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).AnalyzeMealImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_AnalyzeMealImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).AnalyzeMealImage(ctx, req.(*AnalyzeMealImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceService_ServiceDesc is the grpc.ServiceDesc for InferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nutrix.inference.InferenceService",
	HandlerType: (*InferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EstimateVolume",
			Handler:    _InferenceService_EstimateVolume_Handler,
		},
		{
			MethodName: "AnalyzeMealImage",
			Handler:    _InferenceService_AnalyzeMealImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inference.proto",
}
