// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeMealImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw image bytes (JPEG/PNG). Do NOT Base64-encode.
	ImageData []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	// Optional user context for KG reasoning (e.g. "diabetes", "hypertension")
	UserDiseases  []string `protobuf:"bytes,2,rep,name=user_diseases,json=userDiseases,proto3" json:"user_diseases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeMealImageRequest) Reset() {
	*x = AnalyzeMealImageRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeMealImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeMealImageRequest) ProtoMessage() {}

func (x *AnalyzeMealImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeMealImageRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeMealImageRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeMealImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *AnalyzeMealImageRequest) GetUserDiseases() []string {
	if x != nil {
		return x.UserDiseases
	}
	return nil
}

type AnalyzeMealImageResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Computer Vision Output
	FoodLabel           string  `protobuf:"bytes,2,opt,name=food_label,json=foodLabel,proto3" json:"food_label,omitempty"`
	FoodLabelConfidence float32 `protobuf:"fixed32,3,opt,name=food_label_confidence,json=foodLabelConfidence,proto3" json:"food_label_confidence,omitempty"`
	VolumeCm3           float32 `protobuf:"fixed32,4,opt,name=volume_cm3,json=volumeCm3,proto3" json:"volume_cm3,omitempty"`
	MassG               float32 `protobuf:"fixed32,5,opt,name=mass_g,json=massG,proto3" json:"mass_g,omitempty"`
	// Knowledge Graph / Enrichment Output
	Ingredients     []string          `protobuf:"bytes,6,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Safe            bool              `protobuf:"varint,7,opt,name=safe,proto3" json:"safe,omitempty"`
	RiskLevel       string            `protobuf:"bytes,8,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Violations      []*Violation      `protobuf:"bytes,9,rep,name=violations,proto3" json:"violations,omitempty"`
	Recommendations []*Recommendation `protobuf:"bytes,10,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	// Observability
	LatencyMs float32 `protobuf:"fixed32,11,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Reasoning
	EvidencePaths []string `protobuf:"bytes,12,rep,name=evidence_paths,json=evidencePaths,proto3" json:"evidence_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeMealImageResponse) Reset() {
	*x = AnalyzeMealImageResponse{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeMealImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeMealImageResponse) ProtoMessage() {}

func (x *AnalyzeMealImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeMealImageResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeMealImageResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeMealImageResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeMealImageResponse) GetFoodLabel() string {
	if x != nil {
		return x.FoodLabel
	}
	return ""
}

func (x *AnalyzeMealImageResponse) GetFoodLabelConfidence() float32 {
	if x != nil {
		return x.FoodLabelConfidence
	}
	return 0
}

func (x *AnalyzeMealImageResponse) GetVolumeCm3() float32 {
	if x != nil {
		return x.VolumeCm3
	}
	return 0
}

func (x *AnalyzeMealImageResponse) GetMassG() float32 {
	if x != nil {
		return x.MassG
	}
	return 0
}

func (x *AnalyzeMealImageResponse) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *AnalyzeMealImageResponse) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *AnalyzeMealImageResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *AnalyzeMealImageResponse) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *AnalyzeMealImageResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *AnalyzeMealImageResponse) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AnalyzeMealImageResponse) GetEvidencePaths() []string {
	if x != nil {
		return x.EvidencePaths
	}
	return nil
}

type Violation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiseaseId     string                 `protobuf:"bytes,1,opt,name=disease_id,json=diseaseId,proto3" json:"disease_id,omitempty"`
	DiseaseName   string                 `protobuf:"bytes,2,opt,name=disease_name,json=diseaseName,proto3" json:"disease_name,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Violation) Reset() {
	*x = Violation{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Violation) ProtoMessage() {}

func (x *Violation) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Violation.ProtoReflect.Descriptor instead.
func (*Violation) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *Violation) GetDiseaseId() string {
	if x != nil {
		return x.DiseaseId
	}
	return ""
}

func (x *Violation) GetDiseaseName() string {
	if x != nil {
		return x.DiseaseName
	}
	return ""
}

func (x *Violation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Violation) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type Recommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodId        string                 `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	FoodName      string                 `protobuf:"bytes,2,opt,name=food_name,json=foodName,proto3" json:"food_name,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *Recommendation) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

func (x *Recommendation) GetFoodName() string {
	if x != nil {
		return x.FoodName
	}
	return ""
}

func (x *Recommendation) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Recommendation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EstimateVolumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw image bytes (JPEG/PNG). Do NOT Base64-encode.
	// Server will reject payloads exceeding the configured limit.
	ImageData     []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateVolumeRequest) Reset() {
	*x = EstimateVolumeRequest{}
	mi := &file_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateVolumeRequest) ProtoMessage() {}

func (x *EstimateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateVolumeRequest.ProtoReflect.Descriptor instead.
func (*EstimateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{4}
}

func (x *EstimateVolumeRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type EstimateVolumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-generated request ID for end-to-end tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Estimated food volume in cubic centimeters (cm³).
	VolumeCm3 float32 `protobuf:"fixed32,2,opt,name=volume_cm3,json=volumeCm3,proto3" json:"volume_cm3,omitempty"`
	// Model confidence score for the volume estimation [0.0, 1.0].
	VolumeConfidence float32 `protobuf:"fixed32,3,opt,name=volume_confidence,json=volumeConfidence,proto3" json:"volume_confidence,omitempty"`
	// Total server-side latency for this request in milliseconds.
	LatencyMs float32 `protobuf:"fixed32,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Food classification label (e.g., "pho", "com_tam").
	FoodLabel string `protobuf:"bytes,5,opt,name=food_label,json=foodLabel,proto3" json:"food_label,omitempty"`
	// Classifier confidence score [0.0, 1.0].
	FoodLabelConfidence float32 `protobuf:"fixed32,6,opt,name=food_label_confidence,json=foodLabelConfidence,proto3" json:"food_label_confidence,omitempty"`
	// Estimated food mass in grams (g) = volume * density.
	MassG float32 `protobuf:"fixed32,7,opt,name=mass_g,json=massG,proto3" json:"mass_g,omitempty"`
	// Density used for mass calculation (g/cm³).
	DensityGCm3 float32 `protobuf:"fixed32,8,opt,name=density_g_cm3,json=densityGCm3,proto3" json:"density_g_cm3,omitempty"`
	// Explicit flags for presence (replaces 'optional' for cross-lang stability).
	HasMass    bool `protobuf:"varint,9,opt,name=has_mass,json=hasMass,proto3" json:"has_mass,omitempty"`
	HasDensity bool `protobuf:"varint,10,opt,name=has_density,json=hasDensity,proto3" json:"has_density,omitempty"`
	// Tracking where the density came from (e.g. "manual_registry", "unknown_food").
	DensitySource string `protobuf:"bytes,11,opt,name=density_source,json=densitySource,proto3" json:"density_source,omitempty"`
	// Component versions for observability and debugging.
	ClassifierVersion string `protobuf:"bytes,12,opt,name=classifier_version,json=classifierVersion,proto3" json:"classifier_version,omitempty"`
	VolumeVersion     string `protobuf:"bytes,13,opt,name=volume_version,json=volumeVersion,proto3" json:"volume_version,omitempty"`
	DensityVersion    string `protobuf:"bytes,14,opt,name=density_version,json=densityVersion,proto3" json:"density_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EstimateVolumeResponse) Reset() {
	*x = EstimateVolumeResponse{}
	mi := &file_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateVolumeResponse) ProtoMessage() {}

func (x *EstimateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateVolumeResponse.ProtoReflect.Descriptor instead.
func (*EstimateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{5}
}

func (x *EstimateVolumeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EstimateVolumeResponse) GetVolumeCm3() float32 {
	if x != nil {
		return x.VolumeCm3
	}
	return 0
}

func (x *EstimateVolumeResponse) GetVolumeConfidence() float32 {
	if x != nil {
		return x.VolumeConfidence
	}
	return 0
}

func (x *EstimateVolumeResponse) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *EstimateVolumeResponse) GetFoodLabel() string {
	if x != nil {
		return x.FoodLabel
	}
	return ""
}

func (x *EstimateVolumeResponse) GetFoodLabelConfidence() float32 {
	if x != nil {
		return x.FoodLabelConfidence
	}
	return 0
}

func (x *EstimateVolumeResponse) GetMassG() float32 {
	if x != nil {
		return x.MassG
	}
	return 0
}

func (x *EstimateVolumeResponse) GetDensityGCm3() float32 {
	if x != nil {
		return x.DensityGCm3
	}
	return 0
}

func (x *EstimateVolumeResponse) GetHasMass() bool {
	if x != nil {
		return x.HasMass
	}
	return false
}

func (x *EstimateVolumeResponse) GetHasDensity() bool {
	if x != nil {
		return x.HasDensity
	}
	return false
}

func (x *EstimateVolumeResponse) GetDensitySource() string {
	if x != nil {
		return x.DensitySource
	}
	return ""
}

func (x *EstimateVolumeResponse) GetClassifierVersion() string {
	if x != nil {
		return x.ClassifierVersion
	}
	return ""
}

func (x *EstimateVolumeResponse) GetVolumeVersion() string {
	if x != nil {
		return x.VolumeVersion
	}
	return ""
}

func (x *EstimateVolumeResponse) GetDensityVersion() string {
	if x != nil {
		return x.DensityVersion
	}
	return ""
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\x10nutrix.inference\"]\n" +
	"\x17AnalyzeMealImageRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12#\n" +
	"\ruser_diseases\x18\x02 \x03(\tR\fuserDiseases\"\xe6\x03\n" +
	"\x18AnalyzeMealImageResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"food_label\x18\x02 \x01(\tR\tfoodLabel\x122\n" +
	"\x15food_label_confidence\x18\x03 \x01(\x02R\x13foodLabelConfidence\x12\x1d\n" +
	"\n" +
	"volume_cm3\x18\x04 \x01(\x02R\tvolumeCm3\x12\x15\n" +
	"\x06mass_g\x18\x05 \x01(\x02R\x05massG\x12 \n" +
	"\vingredients\x18\x06 \x03(\tR\vingredients\x12\x12\n" +
	"\x04safe\x18\a \x01(\bR\x04safe\x12\x1d\n" +
	"\n" +
	"risk_level\x18\b \x01(\tR\triskLevel\x12;\n" +
	"\n" +
	"violations\x18\t \x03(\v2\x1b.nutrix.inference.ViolationR\n" +
	"violations\x12J\n" +
	"\x0frecommendations\x18\n" +
	" \x03(\v2 .nutrix.inference.RecommendationR\x0frecommendations\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\v \x01(\x02R\tlatencyMs\x12%\n" +
	"\x0eevidence_paths\x18\f \x03(\tR\revidencePaths\"\x8b\x01\n" +
	"\tViolation\x12\x1d\n" +
	"\n" +
	"disease_id\x18\x01 \x01(\tR\tdiseaseId\x12!\n" +
	"\fdisease_name\x18\x02 \x01(\tR\vdiseaseName\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\"t\n" +
	"\x0eRecommendation\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\tR\x06foodId\x12\x1b\n" +
	"\tfood_name\x18\x02 \x01(\tR\bfoodName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"6\n" +
	"\x15EstimateVolumeRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\"\x92\x04\n" +
	"\x16EstimateVolumeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"volume_cm3\x18\x02 \x01(\x02R\tvolumeCm3\x12+\n" +
	"\x11volume_confidence\x18\x03 \x01(\x02R\x10volumeConfidence\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x02R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"food_label\x18\x05 \x01(\tR\tfoodLabel\x122\n" +
	"\x15food_label_confidence\x18\x06 \x01(\x02R\x13foodLabelConfidence\x12\x15\n" +
	"\x06mass_g\x18\a \x01(\x02R\x05massG\x12\"\n" +
	"\rdensity_g_cm3\x18\b \x01(\x02R\vdensityGCm3\x12\x19\n" +
	"\bhas_mass\x18\t \x01(\bR\ahasMass\x12\x1f\n" +
	"\vhas_density\x18\n" +
	" \x01(\bR\n" +
	"hasDensity\x12%\n" +
	"\x0edensity_source\x18\v \x01(\tR\rdensitySource\x12-\n" +
	"\x12classifier_version\x18\f \x01(\tR\x11classifierVersion\x12%\n" +
	"\x0evolume_version\x18\r \x01(\tR\rvolumeVersion\x12'\n" +
	"\x0fdensity_version\x18\x0e \x01(\tR\x0edensityVersion2\xe2\x01\n" +
	"\x10InferenceService\x12c\n" +
	"\x0eEstimateVolume\x12'.nutrix.inference.EstimateVolumeRequest\x1a(.nutrix.inference.EstimateVolumeResponse\x12i\n" +
	"\x10AnalyzeMealImage\x12).nutrix.inference.AnalyzeMealImageRequest\x1a*.nutrix.inference.AnalyzeMealImageResponseB!Z\x1fnutrix/inference/v1;inferencev1b\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inference_proto_goTypes = []any{
	(*AnalyzeMealImageRequest)(nil),  // 0: nutrix.inference.AnalyzeMealImageRequest
	(*AnalyzeMealImageResponse)(nil), // 1: nutrix.inference.AnalyzeMealImageResponse
	(*Violation)(nil),                // 2: nutrix.inference.Violation
	(*Recommendation)(nil),           // 3: nutrix.inference.Recommendation
	(*EstimateVolumeRequest)(nil),    // 4: nutrix.inference.EstimateVolumeRequest
	(*EstimateVolumeResponse)(nil),   // 5: nutrix.inference.EstimateVolumeResponse
}
var file_inference_proto_depIdxs = []int32{
	2, // 0: nutrix.inference.AnalyzeMealImageResponse.violations:type_name -> nutrix.inference.Violation
	3, // 1: nutrix.inference.AnalyzeMealImageResponse.recommendations:type_name -> nutrix.inference.Recommendation
	4, // 2: nutrix.inference.InferenceService.EstimateVolume:input_type -> nutrix.inference.EstimateVolumeRequest
	0, // 3: nutrix.inference.InferenceService.AnalyzeMealImage:input_type -> nutrix.inference.AnalyzeMealImageRequest
	5, // 4: nutrix.inference.InferenceService.EstimateVolume:output_type -> nutrix.inference.EstimateVolumeResponse
	1, // 5: nutrix.inference.InferenceService.AnalyzeMealImage:output_type -> nutrix.inference.AnalyzeMealImageResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
