// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskLevel int32

const (
	RiskLevel_RISK_UNKNOWN  RiskLevel = 0
	RiskLevel_RISK_SAFE     RiskLevel = 1
	RiskLevel_RISK_WARNING  RiskLevel = 2
	RiskLevel_RISK_CRITICAL RiskLevel = 3
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_UNKNOWN",
		1: "RISK_SAFE",
		2: "RISK_WARNING",
		3: "RISK_CRITICAL",
	}
	RiskLevel_value = map[string]int32{
		"RISK_UNKNOWN":  0,
		"RISK_SAFE":     1,
		"RISK_WARNING":  2,
		"RISK_CRITICAL": 3,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_inference_proto_enumTypes[0].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_inference_proto_enumTypes[0]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

type CreateUploadSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadSessionRequest) Reset() {
	*x = CreateUploadSessionRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadSessionRequest) ProtoMessage() {}

func (x *CreateUploadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadSessionRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

type CreateUploadSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UploadSessionId string                 `protobuf:"bytes,1,opt,name=upload_session_id,json=uploadSessionId,proto3" json:"upload_session_id,omitempty"`
	PresignedUrl    string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	ExpiresAt       int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUploadSessionResponse) Reset() {
	*x = CreateUploadSessionResponse{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadSessionResponse) ProtoMessage() {}

func (x *CreateUploadSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadSessionResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUploadSessionResponse) GetUploadSessionId() string {
	if x != nil {
		return x.UploadSessionId
	}
	return ""
}

func (x *CreateUploadSessionResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *CreateUploadSessionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ConfirmUploadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UploadSessionId string                 `protobuf:"bytes,1,opt,name=upload_session_id,json=uploadSessionId,proto3" json:"upload_session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmUploadRequest) Reset() {
	*x = ConfirmUploadRequest{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadRequest) ProtoMessage() {}

func (x *ConfirmUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUploadRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmUploadRequest) GetUploadSessionId() string {
	if x != nil {
		return x.UploadSessionId
	}
	return ""
}

type ConfirmUploadResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UploadSessionId string                 `protobuf:"bytes,1,opt,name=upload_session_id,json=uploadSessionId,proto3" json:"upload_session_id,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmUploadResponse) Reset() {
	*x = ConfirmUploadResponse{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadResponse) ProtoMessage() {}

func (x *ConfirmUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUploadResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmUploadResponse) GetUploadSessionId() string {
	if x != nil {
		return x.UploadSessionId
	}
	return ""
}

func (x *ConfirmUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AnalyzeMealImageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UploadSessionId string                 `protobuf:"bytes,1,opt,name=upload_session_id,json=uploadSessionId,proto3" json:"upload_session_id,omitempty"`
	// Optional user context for KG reasoning (e.g. "diabetes", "hypertension")
	UserDiseases  []string `protobuf:"bytes,2,rep,name=user_diseases,json=userDiseases,proto3" json:"user_diseases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeMealImageRequest) Reset() {
	*x = AnalyzeMealImageRequest{}
	mi := &file_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeMealImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeMealImageRequest) ProtoMessage() {}

func (x *AnalyzeMealImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeMealImageRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeMealImageRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzeMealImageRequest) GetUploadSessionId() string {
	if x != nil {
		return x.UploadSessionId
	}
	return ""
}

func (x *AnalyzeMealImageRequest) GetUserDiseases() []string {
	if x != nil {
		return x.UserDiseases
	}
	return nil
}

type AnalyzeMealImageResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Computer Vision Output
	FoodLabel           string  `protobuf:"bytes,2,opt,name=food_label,json=foodLabel,proto3" json:"food_label,omitempty"`
	FoodLabelConfidence float32 `protobuf:"fixed32,3,opt,name=food_label_confidence,json=foodLabelConfidence,proto3" json:"food_label_confidence,omitempty"`
	VolumeCm3           float32 `protobuf:"fixed32,4,opt,name=volume_cm3,json=volumeCm3,proto3" json:"volume_cm3,omitempty"`
	MassG               float32 `protobuf:"fixed32,5,opt,name=mass_g,json=massG,proto3" json:"mass_g,omitempty"`
	// Knowledge Graph / Enrichment Output
	Ingredients     []string          `protobuf:"bytes,6,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Safe            bool              `protobuf:"varint,7,opt,name=safe,proto3" json:"safe,omitempty"`
	RiskLevel       RiskLevel         `protobuf:"varint,8,opt,name=risk_level,json=riskLevel,proto3,enum=nutrix.inference.RiskLevel" json:"risk_level,omitempty"`
	Violations      []*Violation      `protobuf:"bytes,9,rep,name=violations,proto3" json:"violations,omitempty"`
	Recommendations []*Recommendation `protobuf:"bytes,10,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	// Observability
	LatencyMs float32 `protobuf:"fixed32,11,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Reasoning
	EvidencePaths []*EvidencePath `protobuf:"bytes,12,rep,name=evidence_paths,json=evidencePaths,proto3" json:"evidence_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeMealImageResponse) Reset() {
	*x = AnalyzeMealImageResponse{}
	mi := &file_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeMealImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeMealImageResponse) ProtoMessage() {}

func (x *AnalyzeMealImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeMealImageResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeMealImageResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzeMealImageResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnalyzeMealImageResponse) GetFoodLabel() string {
	if x != nil {
		return x.FoodLabel
	}
	return ""
}

func (x *AnalyzeMealImageResponse) GetFoodLabelConfidence() float32 {
	if x != nil {
		return x.FoodLabelConfidence
	}
	return 0
}

func (x *AnalyzeMealImageResponse) GetVolumeCm3() float32 {
	if x != nil {
		return x.VolumeCm3
	}
	return 0
}

func (x *AnalyzeMealImageResponse) GetMassG() float32 {
	if x != nil {
		return x.MassG
	}
	return 0
}

func (x *AnalyzeMealImageResponse) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *AnalyzeMealImageResponse) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *AnalyzeMealImageResponse) GetRiskLevel() RiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return RiskLevel_RISK_UNKNOWN
}

func (x *AnalyzeMealImageResponse) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *AnalyzeMealImageResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *AnalyzeMealImageResponse) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *AnalyzeMealImageResponse) GetEvidencePaths() []*EvidencePath {
	if x != nil {
		return x.EvidencePaths
	}
	return nil
}

type EvidencePath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidencePath) Reset() {
	*x = EvidencePath{}
	mi := &file_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidencePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidencePath) ProtoMessage() {}

func (x *EvidencePath) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidencePath.ProtoReflect.Descriptor instead.
func (*EvidencePath) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{6}
}

func (x *EvidencePath) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Violation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiseaseId     string                 `protobuf:"bytes,1,opt,name=disease_id,json=diseaseId,proto3" json:"disease_id,omitempty"`
	DiseaseName   string                 `protobuf:"bytes,2,opt,name=disease_name,json=diseaseName,proto3" json:"disease_name,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Violation) Reset() {
	*x = Violation{}
	mi := &file_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Violation) ProtoMessage() {}

func (x *Violation) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Violation.ProtoReflect.Descriptor instead.
func (*Violation) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{7}
}

func (x *Violation) GetDiseaseId() string {
	if x != nil {
		return x.DiseaseId
	}
	return ""
}

func (x *Violation) GetDiseaseName() string {
	if x != nil {
		return x.DiseaseName
	}
	return ""
}

func (x *Violation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Violation) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type Recommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodId        string                 `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	FoodName      string                 `protobuf:"bytes,2,opt,name=food_name,json=foodName,proto3" json:"food_name,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{8}
}

func (x *Recommendation) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

func (x *Recommendation) GetFoodName() string {
	if x != nil {
		return x.FoodName
	}
	return ""
}

func (x *Recommendation) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Recommendation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EstimateVolumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw image bytes (JPEG/PNG). Do NOT Base64-encode.
	// Server will reject payloads exceeding the configured limit.
	ImageData     []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateVolumeRequest) Reset() {
	*x = EstimateVolumeRequest{}
	mi := &file_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateVolumeRequest) ProtoMessage() {}

func (x *EstimateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateVolumeRequest.ProtoReflect.Descriptor instead.
func (*EstimateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{9}
}

func (x *EstimateVolumeRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type EstimateVolumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-generated request ID for end-to-end tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Estimated food volume in cubic centimeters (cm³).
	VolumeCm3 float32 `protobuf:"fixed32,2,opt,name=volume_cm3,json=volumeCm3,proto3" json:"volume_cm3,omitempty"`
	// Model confidence score for the volume estimation [0.0, 1.0].
	VolumeConfidence float32 `protobuf:"fixed32,3,opt,name=volume_confidence,json=volumeConfidence,proto3" json:"volume_confidence,omitempty"`
	// Total server-side latency for this request in milliseconds.
	LatencyMs float32 `protobuf:"fixed32,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Food classification label (e.g., "pho", "com_tam").
	FoodLabel string `protobuf:"bytes,5,opt,name=food_label,json=foodLabel,proto3" json:"food_label,omitempty"`
	// Classifier confidence score [0.0, 1.0].
	FoodLabelConfidence float32 `protobuf:"fixed32,6,opt,name=food_label_confidence,json=foodLabelConfidence,proto3" json:"food_label_confidence,omitempty"`
	// Estimated food mass in grams (g) = volume * density.
	MassG float32 `protobuf:"fixed32,7,opt,name=mass_g,json=massG,proto3" json:"mass_g,omitempty"`
	// Density used for mass calculation (g/cm³).
	DensityGCm3 float32 `protobuf:"fixed32,8,opt,name=density_g_cm3,json=densityGCm3,proto3" json:"density_g_cm3,omitempty"`
	// Explicit flags for presence (replaces 'optional' for cross-lang stability).
	HasMass    bool `protobuf:"varint,9,opt,name=has_mass,json=hasMass,proto3" json:"has_mass,omitempty"`
	HasDensity bool `protobuf:"varint,10,opt,name=has_density,json=hasDensity,proto3" json:"has_density,omitempty"`
	// Tracking where the density came from (e.g. "manual_registry", "unknown_food").
	DensitySource string `protobuf:"bytes,11,opt,name=density_source,json=densitySource,proto3" json:"density_source,omitempty"`
	// Component versions for observability and debugging.
	ClassifierVersion string `protobuf:"bytes,12,opt,name=classifier_version,json=classifierVersion,proto3" json:"classifier_version,omitempty"`
	VolumeVersion     string `protobuf:"bytes,13,opt,name=volume_version,json=volumeVersion,proto3" json:"volume_version,omitempty"`
	DensityVersion    string `protobuf:"bytes,14,opt,name=density_version,json=densityVersion,proto3" json:"density_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EstimateVolumeResponse) Reset() {
	*x = EstimateVolumeResponse{}
	mi := &file_inference_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateVolumeResponse) ProtoMessage() {}

func (x *EstimateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateVolumeResponse.ProtoReflect.Descriptor instead.
func (*EstimateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{10}
}

func (x *EstimateVolumeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EstimateVolumeResponse) GetVolumeCm3() float32 {
	if x != nil {
		return x.VolumeCm3
	}
	return 0
}

func (x *EstimateVolumeResponse) GetVolumeConfidence() float32 {
	if x != nil {
		return x.VolumeConfidence
	}
	return 0
}

func (x *EstimateVolumeResponse) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *EstimateVolumeResponse) GetFoodLabel() string {
	if x != nil {
		return x.FoodLabel
	}
	return ""
}

func (x *EstimateVolumeResponse) GetFoodLabelConfidence() float32 {
	if x != nil {
		return x.FoodLabelConfidence
	}
	return 0
}

func (x *EstimateVolumeResponse) GetMassG() float32 {
	if x != nil {
		return x.MassG
	}
	return 0
}

func (x *EstimateVolumeResponse) GetDensityGCm3() float32 {
	if x != nil {
		return x.DensityGCm3
	}
	return 0
}

func (x *EstimateVolumeResponse) GetHasMass() bool {
	if x != nil {
		return x.HasMass
	}
	return false
}

func (x *EstimateVolumeResponse) GetHasDensity() bool {
	if x != nil {
		return x.HasDensity
	}
	return false
}

func (x *EstimateVolumeResponse) GetDensitySource() string {
	if x != nil {
		return x.DensitySource
	}
	return ""
}

func (x *EstimateVolumeResponse) GetClassifierVersion() string {
	if x != nil {
		return x.ClassifierVersion
	}
	return ""
}

func (x *EstimateVolumeResponse) GetVolumeVersion() string {
	if x != nil {
		return x.VolumeVersion
	}
	return ""
}

func (x *EstimateVolumeResponse) GetDensityVersion() string {
	if x != nil {
		return x.DensityVersion
	}
	return ""
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\x10nutrix.inference\"\x1c\n" +
	"\x1aCreateUploadSessionRequest\"\x8d\x01\n" +
	"\x1bCreateUploadSessionResponse\x12*\n" +
	"\x11upload_session_id\x18\x01 \x01(\tR\x0fuploadSessionId\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"B\n" +
	"\x14ConfirmUploadRequest\x12*\n" +
	"\x11upload_session_id\x18\x01 \x01(\tR\x0fuploadSessionId\"]\n" +
	"\x15ConfirmUploadResponse\x12*\n" +
	"\x11upload_session_id\x18\x01 \x01(\tR\x0fuploadSessionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"j\n" +
	"\x17AnalyzeMealImageRequest\x12*\n" +
	"\x11upload_session_id\x18\x01 \x01(\tR\x0fuploadSessionId\x12#\n" +
	"\ruser_diseases\x18\x02 \x03(\tR\fuserDiseases\"\xa3\x04\n" +
	"\x18AnalyzeMealImageResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"food_label\x18\x02 \x01(\tR\tfoodLabel\x122\n" +
	"\x15food_label_confidence\x18\x03 \x01(\x02R\x13foodLabelConfidence\x12\x1d\n" +
	"\n" +
	"volume_cm3\x18\x04 \x01(\x02R\tvolumeCm3\x12\x15\n" +
	"\x06mass_g\x18\x05 \x01(\x02R\x05massG\x12 \n" +
	"\vingredients\x18\x06 \x03(\tR\vingredients\x12\x12\n" +
	"\x04safe\x18\a \x01(\bR\x04safe\x12:\n" +
	"\n" +
	"risk_level\x18\b \x01(\x0e2\x1b.nutrix.inference.RiskLevelR\triskLevel\x12;\n" +
	"\n" +
	"violations\x18\t \x03(\v2\x1b.nutrix.inference.ViolationR\n" +
	"violations\x12J\n" +
	"\x0frecommendations\x18\n" +
	" \x03(\v2 .nutrix.inference.RecommendationR\x0frecommendations\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\v \x01(\x02R\tlatencyMs\x12E\n" +
	"\x0eevidence_paths\x18\f \x03(\v2\x1e.nutrix.inference.EvidencePathR\revidencePaths\"$\n" +
	"\fEvidencePath\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\"\x8b\x01\n" +
	"\tViolation\x12\x1d\n" +
	"\n" +
	"disease_id\x18\x01 \x01(\tR\tdiseaseId\x12!\n" +
	"\fdisease_name\x18\x02 \x01(\tR\vdiseaseName\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\"t\n" +
	"\x0eRecommendation\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\tR\x06foodId\x12\x1b\n" +
	"\tfood_name\x18\x02 \x01(\tR\bfoodName\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"6\n" +
	"\x15EstimateVolumeRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\"\x92\x04\n" +
	"\x16EstimateVolumeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"volume_cm3\x18\x02 \x01(\x02R\tvolumeCm3\x12+\n" +
	"\x11volume_confidence\x18\x03 \x01(\x02R\x10volumeConfidence\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x02R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"food_label\x18\x05 \x01(\tR\tfoodLabel\x122\n" +
	"\x15food_label_confidence\x18\x06 \x01(\x02R\x13foodLabelConfidence\x12\x15\n" +
	"\x06mass_g\x18\a \x01(\x02R\x05massG\x12\"\n" +
	"\rdensity_g_cm3\x18\b \x01(\x02R\vdensityGCm3\x12\x19\n" +
	"\bhas_mass\x18\t \x01(\bR\ahasMass\x12\x1f\n" +
	"\vhas_density\x18\n" +
	" \x01(\bR\n" +
	"hasDensity\x12%\n" +
	"\x0edensity_source\x18\v \x01(\tR\rdensitySource\x12-\n" +
	"\x12classifier_version\x18\f \x01(\tR\x11classifierVersion\x12%\n" +
	"\x0evolume_version\x18\r \x01(\tR\rvolumeVersion\x12'\n" +
	"\x0fdensity_version\x18\x0e \x01(\tR\x0edensityVersion*Q\n" +
	"\tRiskLevel\x12\x10\n" +
	"\fRISK_UNKNOWN\x10\x00\x12\r\n" +
	"\tRISK_SAFE\x10\x01\x12\x10\n" +
	"\fRISK_WARNING\x10\x02\x12\x11\n" +
	"\rRISK_CRITICAL\x10\x032\xb8\x03\n" +
	"\x10InferenceService\x12c\n" +
	"\x0eEstimateVolume\x12'.nutrix.inference.EstimateVolumeRequest\x1a(.nutrix.inference.EstimateVolumeResponse\x12r\n" +
	"\x13CreateUploadSession\x12,.nutrix.inference.CreateUploadSessionRequest\x1a-.nutrix.inference.CreateUploadSessionResponse\x12`\n" +
	"\rConfirmUpload\x12&.nutrix.inference.ConfirmUploadRequest\x1a'.nutrix.inference.ConfirmUploadResponse\x12i\n" +
	"\x10AnalyzeMealImage\x12).nutrix.inference.AnalyzeMealImageRequest\x1a*.nutrix.inference.AnalyzeMealImageResponseB!Z\x1fnutrix/inference/v1;inferencev1b\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_inference_proto_goTypes = []any{
	(RiskLevel)(0),                      // 0: nutrix.inference.RiskLevel
	(*CreateUploadSessionRequest)(nil),  // 1: nutrix.inference.CreateUploadSessionRequest
	(*CreateUploadSessionResponse)(nil), // 2: nutrix.inference.CreateUploadSessionResponse
	(*ConfirmUploadRequest)(nil),        // 3: nutrix.inference.ConfirmUploadRequest
	(*ConfirmUploadResponse)(nil),       // 4: nutrix.inference.ConfirmUploadResponse
	(*AnalyzeMealImageRequest)(nil),     // 5: nutrix.inference.AnalyzeMealImageRequest
	(*AnalyzeMealImageResponse)(nil),    // 6: nutrix.inference.AnalyzeMealImageResponse
	(*EvidencePath)(nil),                // 7: nutrix.inference.EvidencePath
	(*Violation)(nil),                   // 8: nutrix.inference.Violation
	(*Recommendation)(nil),              // 9: nutrix.inference.Recommendation
	(*EstimateVolumeRequest)(nil),       // 10: nutrix.inference.EstimateVolumeRequest
	(*EstimateVolumeResponse)(nil),      // 11: nutrix.inference.EstimateVolumeResponse
}
var file_inference_proto_depIdxs = []int32{
	0,  // 0: nutrix.inference.AnalyzeMealImageResponse.risk_level:type_name -> nutrix.inference.RiskLevel
	8,  // 1: nutrix.inference.AnalyzeMealImageResponse.violations:type_name -> nutrix.inference.Violation
	9,  // 2: nutrix.inference.AnalyzeMealImageResponse.recommendations:type_name -> nutrix.inference.Recommendation
	7,  // 3: nutrix.inference.AnalyzeMealImageResponse.evidence_paths:type_name -> nutrix.inference.EvidencePath
	10, // 4: nutrix.inference.InferenceService.EstimateVolume:input_type -> nutrix.inference.EstimateVolumeRequest
	1,  // 5: nutrix.inference.InferenceService.CreateUploadSession:input_type -> nutrix.inference.CreateUploadSessionRequest
	3,  // 6: nutrix.inference.InferenceService.ConfirmUpload:input_type -> nutrix.inference.ConfirmUploadRequest
	5,  // 7: nutrix.inference.InferenceService.AnalyzeMealImage:input_type -> nutrix.inference.AnalyzeMealImageRequest
	11, // 8: nutrix.inference.InferenceService.EstimateVolume:output_type -> nutrix.inference.EstimateVolumeResponse
	2,  // 9: nutrix.inference.InferenceService.CreateUploadSession:output_type -> nutrix.inference.CreateUploadSessionResponse
	4,  // 10: nutrix.inference.InferenceService.ConfirmUpload:output_type -> nutrix.inference.ConfirmUploadResponse
	6,  // 11: nutrix.inference.InferenceService.AnalyzeMealImage:output_type -> nutrix.inference.AnalyzeMealImageResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		EnumInfos:         file_inference_proto_enumTypes,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
