// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: v1/common.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskLevel int32

const (
	RiskLevel_RISK_LEVEL_UNSPECIFIED RiskLevel = 0
	RiskLevel_RISK_LEVEL_SAFE        RiskLevel = 1
	RiskLevel_RISK_LEVEL_LOW         RiskLevel = 2
	RiskLevel_RISK_LEVEL_MEDIUM      RiskLevel = 3
	RiskLevel_RISK_LEVEL_HIGH        RiskLevel = 4
	RiskLevel_RISK_LEVEL_CRITICAL    RiskLevel = 5
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_LEVEL_UNSPECIFIED",
		1: "RISK_LEVEL_SAFE",
		2: "RISK_LEVEL_LOW",
		3: "RISK_LEVEL_MEDIUM",
		4: "RISK_LEVEL_HIGH",
		5: "RISK_LEVEL_CRITICAL",
	}
	RiskLevel_value = map[string]int32{
		"RISK_LEVEL_UNSPECIFIED": 0,
		"RISK_LEVEL_SAFE":        1,
		"RISK_LEVEL_LOW":         2,
		"RISK_LEVEL_MEDIUM":      3,
		"RISK_LEVEL_HIGH":        4,
		"RISK_LEVEL_CRITICAL":    5,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_common_proto_enumTypes[0].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_v1_common_proto_enumTypes[0]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{0}
}

type RequestMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMeta) Reset() {
	*x = RequestMeta{}
	mi := &file_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMeta) ProtoMessage() {}

func (x *RequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMeta.ProtoReflect.Descriptor instead.
func (*RequestMeta) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMeta) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type EvidenceNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceNode) Reset() {
	*x = EvidenceNode{}
	mi := &file_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceNode) ProtoMessage() {}

func (x *EvidenceNode) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceNode.ProtoReflect.Descriptor instead.
func (*EvidenceNode) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *EvidenceNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EvidenceNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *EvidenceNode) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type EvidenceStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Node          *EvidenceNode          `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceStep) Reset() {
	*x = EvidenceStep{}
	mi := &file_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceStep) ProtoMessage() {}

func (x *EvidenceStep) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceStep.ProtoReflect.Descriptor instead.
func (*EvidenceStep) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *EvidenceStep) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EvidenceStep) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EvidenceStep) GetNode() *EvidenceNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type EvidencePath struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DiseaseId       string                 `protobuf:"bytes,1,opt,name=disease_id,json=diseaseId,proto3" json:"disease_id,omitempty"`
	Steps           []*EvidenceStep        `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	RuleDescription string                 `protobuf:"bytes,3,opt,name=rule_description,json=ruleDescription,proto3" json:"rule_description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EvidencePath) Reset() {
	*x = EvidencePath{}
	mi := &file_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidencePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidencePath) ProtoMessage() {}

func (x *EvidencePath) ProtoReflect() protoreflect.Message {
	mi := &file_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidencePath.ProtoReflect.Descriptor instead.
func (*EvidencePath) Descriptor() ([]byte, []int) {
	return file_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *EvidencePath) GetDiseaseId() string {
	if x != nil {
		return x.DiseaseId
	}
	return ""
}

func (x *EvidencePath) GetSteps() []*EvidenceStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *EvidencePath) GetRuleDescription() string {
	if x != nil {
		return x.RuleDescription
	}
	return ""
}

var File_v1_common_proto protoreflect.FileDescriptor

const file_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/common.proto\x12\x10nutrix.common.v1\",\n" +
	"\vRequestMeta\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"a\n" +
	"\fEvidenceNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\"z\n" +
	"\fEvidenceStep\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x122\n" +
	"\x04node\x18\x03 \x01(\v2\x1e.nutrix.common.v1.EvidenceNodeR\x04node\"\x8e\x01\n" +
	"\fEvidencePath\x12\x1d\n" +
	"\n" +
	"disease_id\x18\x01 \x01(\tR\tdiseaseId\x124\n" +
	"\x05steps\x18\x02 \x03(\v2\x1e.nutrix.common.v1.EvidenceStepR\x05steps\x12)\n" +
	"\x10rule_description\x18\x03 \x01(\tR\x0fruleDescription*\x95\x01\n" +
	"\tRiskLevel\x12\x1a\n" +
	"\x16RISK_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fRISK_LEVEL_SAFE\x10\x01\x12\x12\n" +
	"\x0eRISK_LEVEL_LOW\x10\x02\x12\x15\n" +
	"\x11RISK_LEVEL_MEDIUM\x10\x03\x12\x13\n" +
	"\x0fRISK_LEVEL_HIGH\x10\x04\x12\x17\n" +
	"\x13RISK_LEVEL_CRITICAL\x10\x05B0Z.github.com/nutrix/api/proto/common/v1;commonpbb\x06proto3"

var (
	file_v1_common_proto_rawDescOnce sync.Once
	file_v1_common_proto_rawDescData []byte
)

func file_v1_common_proto_rawDescGZIP() []byte {
	file_v1_common_proto_rawDescOnce.Do(func() {
		file_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_common_proto_rawDesc), len(file_v1_common_proto_rawDesc)))
	})
	return file_v1_common_proto_rawDescData
}

var file_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_common_proto_goTypes = []any{
	(RiskLevel)(0),       // 0: nutrix.common.v1.RiskLevel
	(*RequestMeta)(nil),  // 1: nutrix.common.v1.RequestMeta
	(*EvidenceNode)(nil), // 2: nutrix.common.v1.EvidenceNode
	(*EvidenceStep)(nil), // 3: nutrix.common.v1.EvidenceStep
	(*EvidencePath)(nil), // 4: nutrix.common.v1.EvidencePath
}
var file_v1_common_proto_depIdxs = []int32{
	2, // 0: nutrix.common.v1.EvidenceStep.node:type_name -> nutrix.common.v1.EvidenceNode
	3, // 1: nutrix.common.v1.EvidencePath.steps:type_name -> nutrix.common.v1.EvidenceStep
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_common_proto_init() }
func file_v1_common_proto_init() {
	if File_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_common_proto_rawDesc), len(file_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_common_proto_goTypes,
		DependencyIndexes: file_v1_common_proto_depIdxs,
		EnumInfos:         file_v1_common_proto_enumTypes,
		MessageInfos:      file_v1_common_proto_msgTypes,
	}.Build()
	File_v1_common_proto = out.File
	file_v1_common_proto_goTypes = nil
	file_v1_common_proto_depIdxs = nil
}
