// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0--rc2
// source: v1/nutrition_intelligence.proto

package intelligencepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NutritionIntelligenceService_HealthCheck_FullMethodName          = "/nutrix.intelligence.v1.NutritionIntelligenceService/HealthCheck"
	NutritionIntelligenceService_AnalyzeFood_FullMethodName          = "/nutrix.intelligence.v1.NutritionIntelligenceService/AnalyzeFood"
	NutritionIntelligenceService_GetThresholdSnapshot_FullMethodName = "/nutrix.intelligence.v1.NutritionIntelligenceService/GetThresholdSnapshot"
	NutritionIntelligenceService_SubmitFoodCorrection_FullMethodName = "/nutrix.intelligence.v1.NutritionIntelligenceService/SubmitFoodCorrection"
	NutritionIntelligenceService_GetFeedbackAnalytics_FullMethodName = "/nutrix.intelligence.v1.NutritionIntelligenceService/GetFeedbackAnalytics"
	NutritionIntelligenceService_GetNutritionGap_FullMethodName      = "/nutrix.intelligence.v1.NutritionIntelligenceService/GetNutritionGap"
	NutritionIntelligenceService_GetRecommendations_FullMethodName   = "/nutrix.intelligence.v1.NutritionIntelligenceService/GetRecommendations"
	NutritionIntelligenceService_AnalyzeMeal_FullMethodName          = "/nutrix.intelligence.v1.NutritionIntelligenceService/AnalyzeMeal"
)

// NutritionIntelligenceServiceClient is the client API for NutritionIntelligenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NutritionIntelligenceServiceClient interface {
	// Basic connectivity and dependency check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Analyzes a single food for safety and risk
	AnalyzeFood(ctx context.Context, in *AnalyzeFoodRequest, opts ...grpc.CallOption) (*AnalyzeFoodResponse, error)
	// Retrieves a snapshot of the dynamically resolved thresholds
	GetThresholdSnapshot(ctx context.Context, in *GetThresholdSnapshotRequest, opts ...grpc.CallOption) (*GetThresholdSnapshotResponse, error)
	// Submits a user correction for an AI food prediction
	SubmitFoodCorrection(ctx context.Context, in *SubmitFoodCorrectionRequest, opts ...grpc.CallOption) (*SubmitFoodCorrectionResponse, error)
	// Retrieves analytics on user feedback and AI corrections
	GetFeedbackAnalytics(ctx context.Context, in *GetFeedbackAnalyticsRequest, opts ...grpc.CallOption) (*GetFeedbackAnalyticsResponse, error)
	// 15A: Calculates the nutrition gap
	GetNutritionGap(ctx context.Context, in *GetNutritionGapRequest, opts ...grpc.CallOption) (*GetNutritionGapResponse, error)
	// 15B: Gets food recommendations based on gaps
	GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*GetRecommendationsResponse, error)
	// 3C: Analyzes a candidate composite meal for safety, macros, and generates fixes
	AnalyzeMeal(ctx context.Context, in *AnalyzeMealRequest, opts ...grpc.CallOption) (*AnalyzeMealResponse, error)
}

type nutritionIntelligenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNutritionIntelligenceServiceClient(cc grpc.ClientConnInterface) NutritionIntelligenceServiceClient {
	return &nutritionIntelligenceServiceClient{cc}
}

func (c *nutritionIntelligenceServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) AnalyzeFood(ctx context.Context, in *AnalyzeFoodRequest, opts ...grpc.CallOption) (*AnalyzeFoodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeFoodResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_AnalyzeFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) GetThresholdSnapshot(ctx context.Context, in *GetThresholdSnapshotRequest, opts ...grpc.CallOption) (*GetThresholdSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThresholdSnapshotResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_GetThresholdSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) SubmitFoodCorrection(ctx context.Context, in *SubmitFoodCorrectionRequest, opts ...grpc.CallOption) (*SubmitFoodCorrectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitFoodCorrectionResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_SubmitFoodCorrection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) GetFeedbackAnalytics(ctx context.Context, in *GetFeedbackAnalyticsRequest, opts ...grpc.CallOption) (*GetFeedbackAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeedbackAnalyticsResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_GetFeedbackAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) GetNutritionGap(ctx context.Context, in *GetNutritionGapRequest, opts ...grpc.CallOption) (*GetNutritionGapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNutritionGapResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_GetNutritionGap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*GetRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendationsResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) AnalyzeMeal(ctx context.Context, in *AnalyzeMealRequest, opts ...grpc.CallOption) (*AnalyzeMealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeMealResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_AnalyzeMeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NutritionIntelligenceServiceServer is the server API for NutritionIntelligenceService service.
// All implementations must embed UnimplementedNutritionIntelligenceServiceServer
// for forward compatibility.
type NutritionIntelligenceServiceServer interface {
	// Basic connectivity and dependency check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Analyzes a single food for safety and risk
	AnalyzeFood(context.Context, *AnalyzeFoodRequest) (*AnalyzeFoodResponse, error)
	// Retrieves a snapshot of the dynamically resolved thresholds
	GetThresholdSnapshot(context.Context, *GetThresholdSnapshotRequest) (*GetThresholdSnapshotResponse, error)
	// Submits a user correction for an AI food prediction
	SubmitFoodCorrection(context.Context, *SubmitFoodCorrectionRequest) (*SubmitFoodCorrectionResponse, error)
	// Retrieves analytics on user feedback and AI corrections
	GetFeedbackAnalytics(context.Context, *GetFeedbackAnalyticsRequest) (*GetFeedbackAnalyticsResponse, error)
	// 15A: Calculates the nutrition gap
	GetNutritionGap(context.Context, *GetNutritionGapRequest) (*GetNutritionGapResponse, error)
	// 15B: Gets food recommendations based on gaps
	GetRecommendations(context.Context, *GetRecommendationsRequest) (*GetRecommendationsResponse, error)
	// 3C: Analyzes a candidate composite meal for safety, macros, and generates fixes
	AnalyzeMeal(context.Context, *AnalyzeMealRequest) (*AnalyzeMealResponse, error)
	mustEmbedUnimplementedNutritionIntelligenceServiceServer()
}

// UnimplementedNutritionIntelligenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNutritionIntelligenceServiceServer struct{}

func (UnimplementedNutritionIntelligenceServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) AnalyzeFood(context.Context, *AnalyzeFoodRequest) (*AnalyzeFoodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeFood not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) GetThresholdSnapshot(context.Context, *GetThresholdSnapshotRequest) (*GetThresholdSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThresholdSnapshot not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) SubmitFoodCorrection(context.Context, *SubmitFoodCorrectionRequest) (*SubmitFoodCorrectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitFoodCorrection not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) GetFeedbackAnalytics(context.Context, *GetFeedbackAnalyticsRequest) (*GetFeedbackAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeedbackAnalytics not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) GetNutritionGap(context.Context, *GetNutritionGapRequest) (*GetNutritionGapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNutritionGap not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) GetRecommendations(context.Context, *GetRecommendationsRequest) (*GetRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) AnalyzeMeal(context.Context, *AnalyzeMealRequest) (*AnalyzeMealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeMeal not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) mustEmbedUnimplementedNutritionIntelligenceServiceServer() {
}
func (UnimplementedNutritionIntelligenceServiceServer) testEmbeddedByValue() {}

// UnsafeNutritionIntelligenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NutritionIntelligenceServiceServer will
// result in compilation errors.
type UnsafeNutritionIntelligenceServiceServer interface {
	mustEmbedUnimplementedNutritionIntelligenceServiceServer()
}

func RegisterNutritionIntelligenceServiceServer(s grpc.ServiceRegistrar, srv NutritionIntelligenceServiceServer) {
	// If the following call panics, it indicates UnimplementedNutritionIntelligenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NutritionIntelligenceService_ServiceDesc, srv)
}

func _NutritionIntelligenceService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_AnalyzeFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).AnalyzeFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_AnalyzeFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).AnalyzeFood(ctx, req.(*AnalyzeFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_GetThresholdSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThresholdSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).GetThresholdSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_GetThresholdSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).GetThresholdSnapshot(ctx, req.(*GetThresholdSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_SubmitFoodCorrection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFoodCorrectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).SubmitFoodCorrection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_SubmitFoodCorrection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).SubmitFoodCorrection(ctx, req.(*SubmitFoodCorrectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_GetFeedbackAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeedbackAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).GetFeedbackAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_GetFeedbackAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).GetFeedbackAnalytics(ctx, req.(*GetFeedbackAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_GetNutritionGap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNutritionGapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).GetNutritionGap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_GetNutritionGap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).GetNutritionGap(ctx, req.(*GetNutritionGapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).GetRecommendations(ctx, req.(*GetRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_AnalyzeMeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeMealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).AnalyzeMeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_AnalyzeMeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).AnalyzeMeal(ctx, req.(*AnalyzeMealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NutritionIntelligenceService_ServiceDesc is the grpc.ServiceDesc for NutritionIntelligenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NutritionIntelligenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nutrix.intelligence.v1.NutritionIntelligenceService",
	HandlerType: (*NutritionIntelligenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _NutritionIntelligenceService_HealthCheck_Handler,
		},
		{
			MethodName: "AnalyzeFood",
			Handler:    _NutritionIntelligenceService_AnalyzeFood_Handler,
		},
		{
			MethodName: "GetThresholdSnapshot",
			Handler:    _NutritionIntelligenceService_GetThresholdSnapshot_Handler,
		},
		{
			MethodName: "SubmitFoodCorrection",
			Handler:    _NutritionIntelligenceService_SubmitFoodCorrection_Handler,
		},
		{
			MethodName: "GetFeedbackAnalytics",
			Handler:    _NutritionIntelligenceService_GetFeedbackAnalytics_Handler,
		},
		{
			MethodName: "GetNutritionGap",
			Handler:    _NutritionIntelligenceService_GetNutritionGap_Handler,
		},
		{
			MethodName: "GetRecommendations",
			Handler:    _NutritionIntelligenceService_GetRecommendations_Handler,
		},
		{
			MethodName: "AnalyzeMeal",
			Handler:    _NutritionIntelligenceService_AnalyzeMeal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/nutrition_intelligence.proto",
}
