// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0--rc2
// source: nutrition_intelligence.proto

package intelligence

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NutritionIntelligenceService_Ping_FullMethodName              = "/nutrix.intelligence.v1.NutritionIntelligenceService/Ping"
	NutritionIntelligenceService_HealthCheck_FullMethodName       = "/nutrix.intelligence.v1.NutritionIntelligenceService/HealthCheck"
	NutritionIntelligenceService_AnalyzeFood_FullMethodName       = "/nutrix.intelligence.v1.NutritionIntelligenceService/AnalyzeFood"
	NutritionIntelligenceService_BatchAnalyzeFoods_FullMethodName = "/nutrix.intelligence.v1.NutritionIntelligenceService/BatchAnalyzeFoods"
	NutritionIntelligenceService_ExplainFood_FullMethodName       = "/nutrix.intelligence.v1.NutritionIntelligenceService/ExplainFood"
	NutritionIntelligenceService_RecommendFoods_FullMethodName    = "/nutrix.intelligence.v1.NutritionIntelligenceService/RecommendFoods"
)

// NutritionIntelligenceServiceClient is the client API for NutritionIntelligenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ═════════════════════════════════════════════════════════════════
// NutritionIntelligenceService
//
// The single public-facing gRPC service that Go Backend calls.
// Flutter → Go Backend (JWT verify) → gRPC → AI Server → Neo4j
// ═════════════════════════════════════════════════════════════════
type NutritionIntelligenceServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Phase 1: Verify AI Server + Neo4j are operational
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Phase 2: Full food analysis — safety, risks, violations,
	//
	//	summary, alternatives — in a single roundtrip
	AnalyzeFood(ctx context.Context, in *AnalyzeFoodRequest, opts ...grpc.CallOption) (*AnalyzeFoodResponse, error)
	// Phase 3: Batch analysis for Diary (Breakfast/Lunch/Dinner/Snack)
	BatchAnalyzeFoods(ctx context.Context, in *BatchAnalyzeFoodsRequest, opts ...grpc.CallOption) (*BatchAnalyzeFoodsResponse, error)
	// Phase 4: Graph-based explanation (user taps "Why?")
	ExplainFood(ctx context.Context, in *ExplainFoodRequest, opts ...grpc.CallOption) (*ExplainFoodResponse, error)
	// Phase 5 (Sprint 12): Recommendation Ranking Engine
	RecommendFoods(ctx context.Context, in *RecommendFoodsRequest, opts ...grpc.CallOption) (*RecommendFoodsResponse, error)
}

type nutritionIntelligenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNutritionIntelligenceServiceClient(cc grpc.ClientConnInterface) NutritionIntelligenceServiceClient {
	return &nutritionIntelligenceServiceClient{cc}
}

func (c *nutritionIntelligenceServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) AnalyzeFood(ctx context.Context, in *AnalyzeFoodRequest, opts ...grpc.CallOption) (*AnalyzeFoodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeFoodResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_AnalyzeFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) BatchAnalyzeFoods(ctx context.Context, in *BatchAnalyzeFoodsRequest, opts ...grpc.CallOption) (*BatchAnalyzeFoodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchAnalyzeFoodsResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_BatchAnalyzeFoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) ExplainFood(ctx context.Context, in *ExplainFoodRequest, opts ...grpc.CallOption) (*ExplainFoodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainFoodResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_ExplainFood_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nutritionIntelligenceServiceClient) RecommendFoods(ctx context.Context, in *RecommendFoodsRequest, opts ...grpc.CallOption) (*RecommendFoodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendFoodsResponse)
	err := c.cc.Invoke(ctx, NutritionIntelligenceService_RecommendFoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NutritionIntelligenceServiceServer is the server API for NutritionIntelligenceService service.
// All implementations must embed UnimplementedNutritionIntelligenceServiceServer
// for forward compatibility.
//
// ═════════════════════════════════════════════════════════════════
// NutritionIntelligenceService
//
// The single public-facing gRPC service that Go Backend calls.
// Flutter → Go Backend (JWT verify) → gRPC → AI Server → Neo4j
// ═════════════════════════════════════════════════════════════════
type NutritionIntelligenceServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Phase 1: Verify AI Server + Neo4j are operational
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Phase 2: Full food analysis — safety, risks, violations,
	//
	//	summary, alternatives — in a single roundtrip
	AnalyzeFood(context.Context, *AnalyzeFoodRequest) (*AnalyzeFoodResponse, error)
	// Phase 3: Batch analysis for Diary (Breakfast/Lunch/Dinner/Snack)
	BatchAnalyzeFoods(context.Context, *BatchAnalyzeFoodsRequest) (*BatchAnalyzeFoodsResponse, error)
	// Phase 4: Graph-based explanation (user taps "Why?")
	ExplainFood(context.Context, *ExplainFoodRequest) (*ExplainFoodResponse, error)
	// Phase 5 (Sprint 12): Recommendation Ranking Engine
	RecommendFoods(context.Context, *RecommendFoodsRequest) (*RecommendFoodsResponse, error)
	mustEmbedUnimplementedNutritionIntelligenceServiceServer()
}

// UnimplementedNutritionIntelligenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNutritionIntelligenceServiceServer struct{}

func (UnimplementedNutritionIntelligenceServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) AnalyzeFood(context.Context, *AnalyzeFoodRequest) (*AnalyzeFoodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeFood not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) BatchAnalyzeFoods(context.Context, *BatchAnalyzeFoodsRequest) (*BatchAnalyzeFoodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchAnalyzeFoods not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) ExplainFood(context.Context, *ExplainFoodRequest) (*ExplainFoodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainFood not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) RecommendFoods(context.Context, *RecommendFoodsRequest) (*RecommendFoodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecommendFoods not implemented")
}
func (UnimplementedNutritionIntelligenceServiceServer) mustEmbedUnimplementedNutritionIntelligenceServiceServer() {
}
func (UnimplementedNutritionIntelligenceServiceServer) testEmbeddedByValue() {}

// UnsafeNutritionIntelligenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NutritionIntelligenceServiceServer will
// result in compilation errors.
type UnsafeNutritionIntelligenceServiceServer interface {
	mustEmbedUnimplementedNutritionIntelligenceServiceServer()
}

func RegisterNutritionIntelligenceServiceServer(s grpc.ServiceRegistrar, srv NutritionIntelligenceServiceServer) {
	// If the following call panics, it indicates UnimplementedNutritionIntelligenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NutritionIntelligenceService_ServiceDesc, srv)
}

func _NutritionIntelligenceService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_AnalyzeFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).AnalyzeFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_AnalyzeFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).AnalyzeFood(ctx, req.(*AnalyzeFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_BatchAnalyzeFoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchAnalyzeFoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).BatchAnalyzeFoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_BatchAnalyzeFoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).BatchAnalyzeFoods(ctx, req.(*BatchAnalyzeFoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_ExplainFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainFoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).ExplainFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_ExplainFood_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).ExplainFood(ctx, req.(*ExplainFoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NutritionIntelligenceService_RecommendFoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendFoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NutritionIntelligenceServiceServer).RecommendFoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NutritionIntelligenceService_RecommendFoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NutritionIntelligenceServiceServer).RecommendFoods(ctx, req.(*RecommendFoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NutritionIntelligenceService_ServiceDesc is the grpc.ServiceDesc for NutritionIntelligenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NutritionIntelligenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nutrix.intelligence.v1.NutritionIntelligenceService",
	HandlerType: (*NutritionIntelligenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _NutritionIntelligenceService_Ping_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NutritionIntelligenceService_HealthCheck_Handler,
		},
		{
			MethodName: "AnalyzeFood",
			Handler:    _NutritionIntelligenceService_AnalyzeFood_Handler,
		},
		{
			MethodName: "BatchAnalyzeFoods",
			Handler:    _NutritionIntelligenceService_BatchAnalyzeFoods_Handler,
		},
		{
			MethodName: "ExplainFood",
			Handler:    _NutritionIntelligenceService_ExplainFood_Handler,
		},
		{
			MethodName: "RecommendFoods",
			Handler:    _NutritionIntelligenceService_RecommendFoods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nutrition_intelligence.proto",
}
