// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: nutrition_intelligence.proto

package intelligence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	commonpb "nutrix-backend/internal/infrastructure/grpc/pb/commonpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskLevel int32

const (
	RiskLevel_RISK_UNSPECIFIED RiskLevel = 0
	RiskLevel_RISK_SAFE        RiskLevel = 1
	RiskLevel_RISK_LOW         RiskLevel = 2
	RiskLevel_RISK_MODERATE    RiskLevel = 3
	RiskLevel_RISK_HIGH        RiskLevel = 4
	RiskLevel_RISK_SEVERE      RiskLevel = 5
)

// Enum value maps for RiskLevel.
var (
	RiskLevel_name = map[int32]string{
		0: "RISK_UNSPECIFIED",
		1: "RISK_SAFE",
		2: "RISK_LOW",
		3: "RISK_MODERATE",
		4: "RISK_HIGH",
		5: "RISK_SEVERE",
	}
	RiskLevel_value = map[string]int32{
		"RISK_UNSPECIFIED": 0,
		"RISK_SAFE":        1,
		"RISK_LOW":         2,
		"RISK_MODERATE":    3,
		"RISK_HIGH":        4,
		"RISK_SEVERE":      5,
	}
)

func (x RiskLevel) Enum() *RiskLevel {
	p := new(RiskLevel)
	*p = x
	return p
}

func (x RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_nutrition_intelligence_proto_enumTypes[0].Descriptor()
}

func (RiskLevel) Type() protoreflect.EnumType {
	return &file_nutrition_intelligence_proto_enumTypes[0]
}

func (x RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskLevel.Descriptor instead.
func (RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *commonpb.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_nutrition_intelligence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMetadata() *commonpb.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "pong"
	ServerVersion   string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Timestamp       int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Epoch seconds
	ContractVersion string                 `protobuf:"bytes,4,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	ContractCommit  string                 `protobuf:"bytes,5,opt,name=contract_commit,json=contractCommit,proto3" json:"contract_commit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_nutrition_intelligence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingResponse) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *PingResponse) GetContractCommit() string {
	if x != nil {
		return x.ContractCommit
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *commonpb.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_nutrition_intelligence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckRequest) GetMetadata() *commonpb.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // "healthy" | "degraded" | "unhealthy"
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // AI Server version
	Neo4JConnected bool                   `protobuf:"varint,3,opt,name=neo4j_connected,json=neo4jConnected,proto3" json:"neo4j_connected,omitempty"`
	OntologyLoaded bool                   `protobuf:"varint,4,opt,name=ontology_loaded,json=ontologyLoaded,proto3" json:"ontology_loaded,omitempty"`
	DatasetVersion string                 `protobuf:"bytes,5,opt,name=dataset_version,json=datasetVersion,proto3" json:"dataset_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_nutrition_intelligence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetNeo4JConnected() bool {
	if x != nil {
		return x.Neo4JConnected
	}
	return false
}

func (x *HealthCheckResponse) GetOntologyLoaded() bool {
	if x != nil {
		return x.OntologyLoaded
	}
	return false
}

func (x *HealthCheckResponse) GetDatasetVersion() string {
	if x != nil {
		return x.DatasetVersion
	}
	return ""
}

type Violation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"` // e.g., "ALLERGY_SEAFOOD", "BUDGET_SODIUM"
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`     // Human-readable explanation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Violation) Reset() {
	*x = Violation{}
	mi := &file_nutrition_intelligence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Violation) ProtoMessage() {}

func (x *Violation) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Violation.ProtoReflect.Descriptor instead.
func (*Violation) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{4}
}

func (x *Violation) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Violation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AlternativeFood struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodId        string                 `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // Why this is a safe/better alternative
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlternativeFood) Reset() {
	*x = AlternativeFood{}
	mi := &file_nutrition_intelligence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlternativeFood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlternativeFood) ProtoMessage() {}

func (x *AlternativeFood) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlternativeFood.ProtoReflect.Descriptor instead.
func (*AlternativeFood) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{5}
}

func (x *AlternativeFood) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

func (x *AlternativeFood) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlternativeFood) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AnalyzeFoodRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *commonpb.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	User          *commonpb.UserContext     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	FoodId        string                    `protobuf:"bytes,3,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFoodRequest) Reset() {
	*x = AnalyzeFoodRequest{}
	mi := &file_nutrition_intelligence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFoodRequest) ProtoMessage() {}

func (x *AnalyzeFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFoodRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeFoodRequest) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{6}
}

func (x *AnalyzeFoodRequest) GetMetadata() *commonpb.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AnalyzeFoodRequest) GetUser() *commonpb.UserContext {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AnalyzeFoodRequest) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

type AnalyzeFoodResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FoodId               string                 `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Safe                 bool                   `protobuf:"varint,2,opt,name=safe,proto3" json:"safe,omitempty"`
	RiskLevel            RiskLevel              `protobuf:"varint,3,opt,name=risk_level,json=riskLevel,proto3,enum=nutrix.intelligence.v1.RiskLevel" json:"risk_level,omitempty"`
	Summary              string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"` // e.g., "⚠ High Sodium ⚠ Seafood Allergy Risk"
	Violations           []*Violation           `protobuf:"bytes,5,rep,name=violations,proto3" json:"violations,omitempty"`
	ExplanationAvailable bool                   `protobuf:"varint,6,opt,name=explanation_available,json=explanationAvailable,proto3" json:"explanation_available,omitempty"`
	Alternatives         []*AlternativeFood     `protobuf:"bytes,7,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AnalyzeFoodResponse) Reset() {
	*x = AnalyzeFoodResponse{}
	mi := &file_nutrition_intelligence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFoodResponse) ProtoMessage() {}

func (x *AnalyzeFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFoodResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeFoodResponse) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{7}
}

func (x *AnalyzeFoodResponse) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

func (x *AnalyzeFoodResponse) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *AnalyzeFoodResponse) GetRiskLevel() RiskLevel {
	if x != nil {
		return x.RiskLevel
	}
	return RiskLevel_RISK_UNSPECIFIED
}

func (x *AnalyzeFoodResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalyzeFoodResponse) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *AnalyzeFoodResponse) GetExplanationAvailable() bool {
	if x != nil {
		return x.ExplanationAvailable
	}
	return false
}

func (x *AnalyzeFoodResponse) GetAlternatives() []*AlternativeFood {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

type BatchAnalyzeFoodsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *commonpb.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	User          *commonpb.UserContext     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	FoodIds       []string                  `protobuf:"bytes,3,rep,name=food_ids,json=foodIds,proto3" json:"food_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAnalyzeFoodsRequest) Reset() {
	*x = BatchAnalyzeFoodsRequest{}
	mi := &file_nutrition_intelligence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAnalyzeFoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAnalyzeFoodsRequest) ProtoMessage() {}

func (x *BatchAnalyzeFoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAnalyzeFoodsRequest.ProtoReflect.Descriptor instead.
func (*BatchAnalyzeFoodsRequest) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{8}
}

func (x *BatchAnalyzeFoodsRequest) GetMetadata() *commonpb.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BatchAnalyzeFoodsRequest) GetUser() *commonpb.UserContext {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *BatchAnalyzeFoodsRequest) GetFoodIds() []string {
	if x != nil {
		return x.FoodIds
	}
	return nil
}

type FoodAnalysisResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodId        string                 `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Result        *AnalyzeFoodResponse   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoodAnalysisResult) Reset() {
	*x = FoodAnalysisResult{}
	mi := &file_nutrition_intelligence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoodAnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodAnalysisResult) ProtoMessage() {}

func (x *FoodAnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodAnalysisResult.ProtoReflect.Descriptor instead.
func (*FoodAnalysisResult) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{9}
}

func (x *FoodAnalysisResult) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

func (x *FoodAnalysisResult) GetResult() *AnalyzeFoodResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type BatchAnalyzeFoodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FoodAnalysisResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAnalyzeFoodsResponse) Reset() {
	*x = BatchAnalyzeFoodsResponse{}
	mi := &file_nutrition_intelligence_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAnalyzeFoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAnalyzeFoodsResponse) ProtoMessage() {}

func (x *BatchAnalyzeFoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAnalyzeFoodsResponse.ProtoReflect.Descriptor instead.
func (*BatchAnalyzeFoodsResponse) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{10}
}

func (x *BatchAnalyzeFoodsResponse) GetResults() []*FoodAnalysisResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ExplainFoodRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *commonpb.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	User          *commonpb.UserContext     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	FoodId        string                    `protobuf:"bytes,3,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainFoodRequest) Reset() {
	*x = ExplainFoodRequest{}
	mi := &file_nutrition_intelligence_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainFoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainFoodRequest) ProtoMessage() {}

func (x *ExplainFoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainFoodRequest.ProtoReflect.Descriptor instead.
func (*ExplainFoodRequest) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{11}
}

func (x *ExplainFoodRequest) GetMetadata() *commonpb.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExplainFoodRequest) GetUser() *commonpb.UserContext {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ExplainFoodRequest) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

type EvidenceNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // e.g., "Food", "FoodGroup", "Allergen", "Disease"
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceNode) Reset() {
	*x = EvidenceNode{}
	mi := &file_nutrition_intelligence_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceNode) ProtoMessage() {}

func (x *EvidenceNode) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceNode.ProtoReflect.Descriptor instead.
func (*EvidenceNode) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{12}
}

func (x *EvidenceNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *EvidenceNode) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *EvidenceNode) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type ExplainFoodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodId        string                 `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Path          []*EvidenceNode        `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainFoodResponse) Reset() {
	*x = ExplainFoodResponse{}
	mi := &file_nutrition_intelligence_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainFoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainFoodResponse) ProtoMessage() {}

func (x *ExplainFoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainFoodResponse.ProtoReflect.Descriptor instead.
func (*ExplainFoodResponse) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{13}
}

func (x *ExplainFoodResponse) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

func (x *ExplainFoodResponse) GetPath() []*EvidenceNode {
	if x != nil {
		return x.Path
	}
	return nil
}

type RecommendFoodsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Metadata      *commonpb.RequestMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	User          *commonpb.UserContext     `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Limit         int32                     `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendFoodsRequest) Reset() {
	*x = RecommendFoodsRequest{}
	mi := &file_nutrition_intelligence_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendFoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendFoodsRequest) ProtoMessage() {}

func (x *RecommendFoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendFoodsRequest.ProtoReflect.Descriptor instead.
func (*RecommendFoodsRequest) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{14}
}

func (x *RecommendFoodsRequest) GetMetadata() *commonpb.RequestMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RecommendFoodsRequest) GetUser() *commonpb.UserContext {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RecommendFoodsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecommendationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FoodId        string                 `protobuf:"bytes,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Explanation   string                 `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationItem) Reset() {
	*x = RecommendationItem{}
	mi := &file_nutrition_intelligence_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationItem) ProtoMessage() {}

func (x *RecommendationItem) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationItem.ProtoReflect.Descriptor instead.
func (*RecommendationItem) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{15}
}

func (x *RecommendationItem) GetFoodId() string {
	if x != nil {
		return x.FoodId
	}
	return ""
}

func (x *RecommendationItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecommendationItem) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type RecommendFoodsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*RecommendationItem  `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecommendFoodsResponse) Reset() {
	*x = RecommendFoodsResponse{}
	mi := &file_nutrition_intelligence_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendFoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendFoodsResponse) ProtoMessage() {}

func (x *RecommendFoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nutrition_intelligence_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendFoodsResponse.ProtoReflect.Descriptor instead.
func (*RecommendFoodsResponse) Descriptor() ([]byte, []int) {
	return file_nutrition_intelligence_proto_rawDescGZIP(), []int{16}
}

func (x *RecommendFoodsResponse) GetRecommendations() []*RecommendationItem {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_nutrition_intelligence_proto protoreflect.FileDescriptor

const file_nutrition_intelligence_proto_rawDesc = "" +
	"\n" +
	"\x1cnutrition_intelligence.proto\x12\x16nutrix.intelligence.v1\x1a\fcommon.proto\"L\n" +
	"\vPingRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.nutrix.common.v1.RequestMetadataR\bmetadata\"\xbf\x01\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10contract_version\x18\x04 \x01(\tR\x0fcontractVersion\x12'\n" +
	"\x0fcontract_commit\x18\x05 \x01(\tR\x0econtractCommit\"S\n" +
	"\x12HealthCheckRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.nutrix.common.v1.RequestMetadataR\bmetadata\"\xc2\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0fneo4j_connected\x18\x03 \x01(\bR\x0eneo4jConnected\x12'\n" +
	"\x0fontology_loaded\x18\x04 \x01(\bR\x0eontologyLoaded\x12'\n" +
	"\x0fdataset_version\x18\x05 \x01(\tR\x0edatasetVersion\"F\n" +
	"\tViolation\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"V\n" +
	"\x0fAlternativeFood\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\tR\x06foodId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x9f\x01\n" +
	"\x12AnalyzeFoodRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.nutrix.common.v1.RequestMetadataR\bmetadata\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.nutrix.common.v1.UserContextR\x04user\x12\x17\n" +
	"\afood_id\x18\x03 \x01(\tR\x06foodId\"\xe3\x02\n" +
	"\x13AnalyzeFoodResponse\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\tR\x06foodId\x12\x12\n" +
	"\x04safe\x18\x02 \x01(\bR\x04safe\x12@\n" +
	"\n" +
	"risk_level\x18\x03 \x01(\x0e2!.nutrix.intelligence.v1.RiskLevelR\triskLevel\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12A\n" +
	"\n" +
	"violations\x18\x05 \x03(\v2!.nutrix.intelligence.v1.ViolationR\n" +
	"violations\x123\n" +
	"\x15explanation_available\x18\x06 \x01(\bR\x14explanationAvailable\x12K\n" +
	"\falternatives\x18\a \x03(\v2'.nutrix.intelligence.v1.AlternativeFoodR\falternatives\"\xa7\x01\n" +
	"\x18BatchAnalyzeFoodsRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.nutrix.common.v1.RequestMetadataR\bmetadata\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.nutrix.common.v1.UserContextR\x04user\x12\x19\n" +
	"\bfood_ids\x18\x03 \x03(\tR\afoodIds\"r\n" +
	"\x12FoodAnalysisResult\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\tR\x06foodId\x12C\n" +
	"\x06result\x18\x02 \x01(\v2+.nutrix.intelligence.v1.AnalyzeFoodResponseR\x06result\"a\n" +
	"\x19BatchAnalyzeFoodsResponse\x12D\n" +
	"\aresults\x18\x01 \x03(\v2*.nutrix.intelligence.v1.FoodAnalysisResultR\aresults\"\x9f\x01\n" +
	"\x12ExplainFoodRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.nutrix.common.v1.RequestMetadataR\bmetadata\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.nutrix.common.v1.UserContextR\x04user\x12\x17\n" +
	"\afood_id\x18\x03 \x01(\tR\x06foodId\"a\n" +
	"\fEvidenceNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\"h\n" +
	"\x13ExplainFoodResponse\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\tR\x06foodId\x128\n" +
	"\x04path\x18\x02 \x03(\v2$.nutrix.intelligence.v1.EvidenceNodeR\x04path\"\x9f\x01\n" +
	"\x15RecommendFoodsRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.nutrix.common.v1.RequestMetadataR\bmetadata\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.nutrix.common.v1.UserContextR\x04user\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"e\n" +
	"\x12RecommendationItem\x12\x17\n" +
	"\afood_id\x18\x01 \x01(\tR\x06foodId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation\"n\n" +
	"\x16RecommendFoodsResponse\x12T\n" +
	"\x0frecommendations\x18\x01 \x03(\v2*.nutrix.intelligence.v1.RecommendationItemR\x0frecommendations*q\n" +
	"\tRiskLevel\x12\x14\n" +
	"\x10RISK_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tRISK_SAFE\x10\x01\x12\f\n" +
	"\bRISK_LOW\x10\x02\x12\x11\n" +
	"\rRISK_MODERATE\x10\x03\x12\r\n" +
	"\tRISK_HIGH\x10\x04\x12\x0f\n" +
	"\vRISK_SEVERE\x10\x052\x94\x05\n" +
	"\x1cNutritionIntelligenceService\x12Q\n" +
	"\x04Ping\x12#.nutrix.intelligence.v1.PingRequest\x1a$.nutrix.intelligence.v1.PingResponse\x12f\n" +
	"\vHealthCheck\x12*.nutrix.intelligence.v1.HealthCheckRequest\x1a+.nutrix.intelligence.v1.HealthCheckResponse\x12f\n" +
	"\vAnalyzeFood\x12*.nutrix.intelligence.v1.AnalyzeFoodRequest\x1a+.nutrix.intelligence.v1.AnalyzeFoodResponse\x12x\n" +
	"\x11BatchAnalyzeFoods\x120.nutrix.intelligence.v1.BatchAnalyzeFoodsRequest\x1a1.nutrix.intelligence.v1.BatchAnalyzeFoodsResponse\x12f\n" +
	"\vExplainFood\x12*.nutrix.intelligence.v1.ExplainFoodRequest\x1a+.nutrix.intelligence.v1.ExplainFoodResponse\x12o\n" +
	"\x0eRecommendFoods\x12-.nutrix.intelligence.v1.RecommendFoodsRequest\x1a..nutrix.intelligence.v1.RecommendFoodsResponseB=Z;github.com/phuongngo25/nutrix-contracts/gen/go/intelligenceb\x06proto3"

var (
	file_nutrition_intelligence_proto_rawDescOnce sync.Once
	file_nutrition_intelligence_proto_rawDescData []byte
)

func file_nutrition_intelligence_proto_rawDescGZIP() []byte {
	file_nutrition_intelligence_proto_rawDescOnce.Do(func() {
		file_nutrition_intelligence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nutrition_intelligence_proto_rawDesc), len(file_nutrition_intelligence_proto_rawDesc)))
	})
	return file_nutrition_intelligence_proto_rawDescData
}

var file_nutrition_intelligence_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nutrition_intelligence_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_nutrition_intelligence_proto_goTypes = []any{
	(RiskLevel)(0),                    // 0: nutrix.intelligence.v1.RiskLevel
	(*PingRequest)(nil),               // 1: nutrix.intelligence.v1.PingRequest
	(*PingResponse)(nil),              // 2: nutrix.intelligence.v1.PingResponse
	(*HealthCheckRequest)(nil),        // 3: nutrix.intelligence.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 4: nutrix.intelligence.v1.HealthCheckResponse
	(*Violation)(nil),                 // 5: nutrix.intelligence.v1.Violation
	(*AlternativeFood)(nil),           // 6: nutrix.intelligence.v1.AlternativeFood
	(*AnalyzeFoodRequest)(nil),        // 7: nutrix.intelligence.v1.AnalyzeFoodRequest
	(*AnalyzeFoodResponse)(nil),       // 8: nutrix.intelligence.v1.AnalyzeFoodResponse
	(*BatchAnalyzeFoodsRequest)(nil),  // 9: nutrix.intelligence.v1.BatchAnalyzeFoodsRequest
	(*FoodAnalysisResult)(nil),        // 10: nutrix.intelligence.v1.FoodAnalysisResult
	(*BatchAnalyzeFoodsResponse)(nil), // 11: nutrix.intelligence.v1.BatchAnalyzeFoodsResponse
	(*ExplainFoodRequest)(nil),        // 12: nutrix.intelligence.v1.ExplainFoodRequest
	(*EvidenceNode)(nil),              // 13: nutrix.intelligence.v1.EvidenceNode
	(*ExplainFoodResponse)(nil),       // 14: nutrix.intelligence.v1.ExplainFoodResponse
	(*RecommendFoodsRequest)(nil),     // 15: nutrix.intelligence.v1.RecommendFoodsRequest
	(*RecommendationItem)(nil),        // 16: nutrix.intelligence.v1.RecommendationItem
	(*RecommendFoodsResponse)(nil),    // 17: nutrix.intelligence.v1.RecommendFoodsResponse
	(*commonpb.RequestMetadata)(nil),  // 18: nutrix.common.v1.RequestMetadata
	(*commonpb.UserContext)(nil),      // 19: nutrix.common.v1.UserContext
}
var file_nutrition_intelligence_proto_depIdxs = []int32{
	18, // 0: nutrix.intelligence.v1.PingRequest.metadata:type_name -> nutrix.common.v1.RequestMetadata
	18, // 1: nutrix.intelligence.v1.HealthCheckRequest.metadata:type_name -> nutrix.common.v1.RequestMetadata
	18, // 2: nutrix.intelligence.v1.AnalyzeFoodRequest.metadata:type_name -> nutrix.common.v1.RequestMetadata
	19, // 3: nutrix.intelligence.v1.AnalyzeFoodRequest.user:type_name -> nutrix.common.v1.UserContext
	0,  // 4: nutrix.intelligence.v1.AnalyzeFoodResponse.risk_level:type_name -> nutrix.intelligence.v1.RiskLevel
	5,  // 5: nutrix.intelligence.v1.AnalyzeFoodResponse.violations:type_name -> nutrix.intelligence.v1.Violation
	6,  // 6: nutrix.intelligence.v1.AnalyzeFoodResponse.alternatives:type_name -> nutrix.intelligence.v1.AlternativeFood
	18, // 7: nutrix.intelligence.v1.BatchAnalyzeFoodsRequest.metadata:type_name -> nutrix.common.v1.RequestMetadata
	19, // 8: nutrix.intelligence.v1.BatchAnalyzeFoodsRequest.user:type_name -> nutrix.common.v1.UserContext
	8,  // 9: nutrix.intelligence.v1.FoodAnalysisResult.result:type_name -> nutrix.intelligence.v1.AnalyzeFoodResponse
	10, // 10: nutrix.intelligence.v1.BatchAnalyzeFoodsResponse.results:type_name -> nutrix.intelligence.v1.FoodAnalysisResult
	18, // 11: nutrix.intelligence.v1.ExplainFoodRequest.metadata:type_name -> nutrix.common.v1.RequestMetadata
	19, // 12: nutrix.intelligence.v1.ExplainFoodRequest.user:type_name -> nutrix.common.v1.UserContext
	13, // 13: nutrix.intelligence.v1.ExplainFoodResponse.path:type_name -> nutrix.intelligence.v1.EvidenceNode
	18, // 14: nutrix.intelligence.v1.RecommendFoodsRequest.metadata:type_name -> nutrix.common.v1.RequestMetadata
	19, // 15: nutrix.intelligence.v1.RecommendFoodsRequest.user:type_name -> nutrix.common.v1.UserContext
	16, // 16: nutrix.intelligence.v1.RecommendFoodsResponse.recommendations:type_name -> nutrix.intelligence.v1.RecommendationItem
	1,  // 17: nutrix.intelligence.v1.NutritionIntelligenceService.Ping:input_type -> nutrix.intelligence.v1.PingRequest
	3,  // 18: nutrix.intelligence.v1.NutritionIntelligenceService.HealthCheck:input_type -> nutrix.intelligence.v1.HealthCheckRequest
	7,  // 19: nutrix.intelligence.v1.NutritionIntelligenceService.AnalyzeFood:input_type -> nutrix.intelligence.v1.AnalyzeFoodRequest
	9,  // 20: nutrix.intelligence.v1.NutritionIntelligenceService.BatchAnalyzeFoods:input_type -> nutrix.intelligence.v1.BatchAnalyzeFoodsRequest
	12, // 21: nutrix.intelligence.v1.NutritionIntelligenceService.ExplainFood:input_type -> nutrix.intelligence.v1.ExplainFoodRequest
	15, // 22: nutrix.intelligence.v1.NutritionIntelligenceService.RecommendFoods:input_type -> nutrix.intelligence.v1.RecommendFoodsRequest
	2,  // 23: nutrix.intelligence.v1.NutritionIntelligenceService.Ping:output_type -> nutrix.intelligence.v1.PingResponse
	4,  // 24: nutrix.intelligence.v1.NutritionIntelligenceService.HealthCheck:output_type -> nutrix.intelligence.v1.HealthCheckResponse
	8,  // 25: nutrix.intelligence.v1.NutritionIntelligenceService.AnalyzeFood:output_type -> nutrix.intelligence.v1.AnalyzeFoodResponse
	11, // 26: nutrix.intelligence.v1.NutritionIntelligenceService.BatchAnalyzeFoods:output_type -> nutrix.intelligence.v1.BatchAnalyzeFoodsResponse
	14, // 27: nutrix.intelligence.v1.NutritionIntelligenceService.ExplainFood:output_type -> nutrix.intelligence.v1.ExplainFoodResponse
	17, // 28: nutrix.intelligence.v1.NutritionIntelligenceService.RecommendFoods:output_type -> nutrix.intelligence.v1.RecommendFoodsResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_nutrition_intelligence_proto_init() }
func file_nutrition_intelligence_proto_init() {
	if File_nutrition_intelligence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nutrition_intelligence_proto_rawDesc), len(file_nutrition_intelligence_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nutrition_intelligence_proto_goTypes,
		DependencyIndexes: file_nutrition_intelligence_proto_depIdxs,
		EnumInfos:         file_nutrition_intelligence_proto_enumTypes,
		MessageInfos:      file_nutrition_intelligence_proto_msgTypes,
	}.Build()
	File_nutrition_intelligence_proto = out.File
	file_nutrition_intelligence_proto_goTypes = nil
	file_nutrition_intelligence_proto_depIdxs = nil
}
