package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// UserStreak represents the derived cache table in Postgres.
// All values here are generated by the StreakEvaluationService and are 100% derived from snapshots + logs.
type UserStreak struct {
	UserID            uuid.UUID `gorm:"type:uuid;primaryKey" json:"user_id"`
	CurrentStreak     int       `gorm:"not null" json:"current_streak"`
	LongestStreak     int       `gorm:"not null" json:"longest_streak"`
	LastEvaluatedDate time.Time `gorm:"type:date;not null" json:"last_evaluated_date"` // DATE in GORM / Postgres
	CreatedAt         time.Time `gorm:"autoCreateTime" json:"created_at"`
	UpdatedAt         time.Time `gorm:"autoUpdateTime" json:"updated_at"`
}

// TableName overrides the table name to match database conventions.
func (UserStreak) TableName() string {
	return "user_streaks"
}

// StreakRepository defines database capabilities for caching user streaks.
type StreakRepository interface {
	GetStreak(ctx context.Context, userID uuid.UUID) (*UserStreak, error)
	UpsertStreak(ctx context.Context, streak *UserStreak) error
}
