// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EstimateVolumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw image bytes (JPEG/PNG). Do NOT Base64-encode.
	// Server will reject payloads exceeding the configured limit.
	ImageData     []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateVolumeRequest) Reset() {
	*x = EstimateVolumeRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateVolumeRequest) ProtoMessage() {}

func (x *EstimateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateVolumeRequest.ProtoReflect.Descriptor instead.
func (*EstimateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *EstimateVolumeRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type EstimateVolumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-generated request ID for end-to-end tracing.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Estimated food volume in cubic centimeters (cm³).
	VolumeCm3 float32 `protobuf:"fixed32,2,opt,name=volume_cm3,json=volumeCm3,proto3" json:"volume_cm3,omitempty"`
	// Model confidence score for the volume estimation [0.0, 1.0].
	VolumeConfidence float32 `protobuf:"fixed32,3,opt,name=volume_confidence,json=volumeConfidence,proto3" json:"volume_confidence,omitempty"`
	// Total server-side latency for this request in milliseconds.
	LatencyMs float32 `protobuf:"fixed32,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Food classification label (e.g., "pho", "com_tam").
	FoodLabel string `protobuf:"bytes,5,opt,name=food_label,json=foodLabel,proto3" json:"food_label,omitempty"`
	// Classifier confidence score [0.0, 1.0].
	FoodLabelConfidence float32 `protobuf:"fixed32,6,opt,name=food_label_confidence,json=foodLabelConfidence,proto3" json:"food_label_confidence,omitempty"`
	// Estimated food mass in grams (g) = volume * density.
	MassG float32 `protobuf:"fixed32,7,opt,name=mass_g,json=massG,proto3" json:"mass_g,omitempty"`
	// Density used for mass calculation (g/cm³).
	DensityGCm3 float32 `protobuf:"fixed32,8,opt,name=density_g_cm3,json=densityGCm3,proto3" json:"density_g_cm3,omitempty"`
	// Explicit flags for presence (replaces 'optional' for cross-lang stability).
	HasMass    bool `protobuf:"varint,9,opt,name=has_mass,json=hasMass,proto3" json:"has_mass,omitempty"`
	HasDensity bool `protobuf:"varint,10,opt,name=has_density,json=hasDensity,proto3" json:"has_density,omitempty"`
	// Tracking where the density came from (e.g. "manual_registry", "unknown_food").
	DensitySource string `protobuf:"bytes,11,opt,name=density_source,json=densitySource,proto3" json:"density_source,omitempty"`
	// Component versions for observability and debugging.
	ClassifierVersion string `protobuf:"bytes,12,opt,name=classifier_version,json=classifierVersion,proto3" json:"classifier_version,omitempty"`
	VolumeVersion     string `protobuf:"bytes,13,opt,name=volume_version,json=volumeVersion,proto3" json:"volume_version,omitempty"`
	DensityVersion    string `protobuf:"bytes,14,opt,name=density_version,json=densityVersion,proto3" json:"density_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EstimateVolumeResponse) Reset() {
	*x = EstimateVolumeResponse{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateVolumeResponse) ProtoMessage() {}

func (x *EstimateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateVolumeResponse.ProtoReflect.Descriptor instead.
func (*EstimateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *EstimateVolumeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EstimateVolumeResponse) GetVolumeCm3() float32 {
	if x != nil {
		return x.VolumeCm3
	}
	return 0
}

func (x *EstimateVolumeResponse) GetVolumeConfidence() float32 {
	if x != nil {
		return x.VolumeConfidence
	}
	return 0
}

func (x *EstimateVolumeResponse) GetLatencyMs() float32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *EstimateVolumeResponse) GetFoodLabel() string {
	if x != nil {
		return x.FoodLabel
	}
	return ""
}

func (x *EstimateVolumeResponse) GetFoodLabelConfidence() float32 {
	if x != nil {
		return x.FoodLabelConfidence
	}
	return 0
}

func (x *EstimateVolumeResponse) GetMassG() float32 {
	if x != nil {
		return x.MassG
	}
	return 0
}

func (x *EstimateVolumeResponse) GetDensityGCm3() float32 {
	if x != nil {
		return x.DensityGCm3
	}
	return 0
}

func (x *EstimateVolumeResponse) GetHasMass() bool {
	if x != nil {
		return x.HasMass
	}
	return false
}

func (x *EstimateVolumeResponse) GetHasDensity() bool {
	if x != nil {
		return x.HasDensity
	}
	return false
}

func (x *EstimateVolumeResponse) GetDensitySource() string {
	if x != nil {
		return x.DensitySource
	}
	return ""
}

func (x *EstimateVolumeResponse) GetClassifierVersion() string {
	if x != nil {
		return x.ClassifierVersion
	}
	return ""
}

func (x *EstimateVolumeResponse) GetVolumeVersion() string {
	if x != nil {
		return x.VolumeVersion
	}
	return ""
}

func (x *EstimateVolumeResponse) GetDensityVersion() string {
	if x != nil {
		return x.DensityVersion
	}
	return ""
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\x10nutrix.inference\"6\n" +
	"\x15EstimateVolumeRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\"\x92\x04\n" +
	"\x16EstimateVolumeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"volume_cm3\x18\x02 \x01(\x02R\tvolumeCm3\x12+\n" +
	"\x11volume_confidence\x18\x03 \x01(\x02R\x10volumeConfidence\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x02R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"food_label\x18\x05 \x01(\tR\tfoodLabel\x122\n" +
	"\x15food_label_confidence\x18\x06 \x01(\x02R\x13foodLabelConfidence\x12\x15\n" +
	"\x06mass_g\x18\a \x01(\x02R\x05massG\x12\"\n" +
	"\rdensity_g_cm3\x18\b \x01(\x02R\vdensityGCm3\x12\x19\n" +
	"\bhas_mass\x18\t \x01(\bR\ahasMass\x12\x1f\n" +
	"\vhas_density\x18\n" +
	" \x01(\bR\n" +
	"hasDensity\x12%\n" +
	"\x0edensity_source\x18\v \x01(\tR\rdensitySource\x12-\n" +
	"\x12classifier_version\x18\f \x01(\tR\x11classifierVersion\x12%\n" +
	"\x0evolume_version\x18\r \x01(\tR\rvolumeVersion\x12'\n" +
	"\x0fdensity_version\x18\x0e \x01(\tR\x0edensityVersion2w\n" +
	"\x10InferenceService\x12c\n" +
	"\x0eEstimateVolume\x12'.nutrix.inference.EstimateVolumeRequest\x1a(.nutrix.inference.EstimateVolumeResponseB!Z\x1fnutrix/inference/v1;inferencev1b\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inference_proto_goTypes = []any{
	(*EstimateVolumeRequest)(nil),  // 0: nutrix.inference.EstimateVolumeRequest
	(*EstimateVolumeResponse)(nil), // 1: nutrix.inference.EstimateVolumeResponse
}
var file_inference_proto_depIdxs = []int32{
	0, // 0: nutrix.inference.InferenceService.EstimateVolume:input_type -> nutrix.inference.EstimateVolumeRequest
	1, // 1: nutrix.inference.InferenceService.EstimateVolume:output_type -> nutrix.inference.EstimateVolumeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
